### ISSUE TITLE
Not ignoring minimized windows (sometimes)

### ISSUE THREAD

**Issue by zehkira** [zehkira/pytyle1x#1]
_Manjaro/XFCE, PyTyle 0.7.9_

When Firefox is minimized, PyTyle treats it as if it wasn't, leaving empty space where it expects the browser to be. As far as I know, this does not happen with any other app.

Need to test with different apps and desktop environments.

**Comment by programical** [comment]
Reboot fixed this. Still need to find the cause though.

**Comment by programical** [comment]
I still can't consistently reproduce this bug.

**Comment by programical** [comment]
I haven't encountered this bug in a while. All attempts to reproduce it failed. Closing for now.

**Comment by programical** [comment]
I think I got it. This is caused by Godot.

**Comment by programical** [comment]
Today I encountered this issue again despite not using Godot...
