### ISSUE TITLE
PyTyle won't start

### ISSUE THREAD

**Issue by hellisabove** [zehkira/pytyle1x#14]
6/17/2021 at 12:16:54:    PyTyle started.
6/17/2021 at 12:16:54:    Fatal error!
6/17/2021 at 12:16:54:    Traceback (most recent call last):
  File "/usr/local/bin/pytyle1x", line 42, in <module>
    State.reload_active()
  File "/usr/local/lib/python3.9/dist-packages/PyTyle/State.py", line 167, in reload_active
    State._DESKTOP = State.get_desktops()[PROBE.get_desktop()]
  File "/usr/local/lib/python3.9/dist-packages/PyTyle/Probe.py", line 98, in get_desktop
    return self.get_root().get_full_property(
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by zehkira** [comment]
What window manager/desktop environment are you using? Do you have more than one screen?

**Comment by hellisabove** [comment]
I use gnome with Debian 11 on only one screen

**Comment by zehkira** [comment]
Looks like another issue with Mutter. I'll see what I can do.

**Comment by hellisabove** [comment]
Apparently it's an issue with debian's mutter because on manjaro gnome it works without problem.

**Comment by zehkira** [comment]
Does the tiling actually work on Manjaro Gnome for you? I'm able to start PyTyle, but there's no tiling happening.

**Comment by hellisabove** [comment]
For me it’s working

**Comment by zehkira** [comment]
I've pushed a fix to the repo. On your Debian Gnome:
1. Uninstall PyTyle
2. Download or clone this repository
3. Install PyTyle from the downloaded repository (`./setup.py install` as root)

Tell me if it works.

**Comment by hellisabove** [comment]
Thanks, now it works
